### ISSUE TITLE
Denied access to fast-md5 Maven dependency with HTTP

### ISSUE THREAD

**Issue by jlegrand62** [OpenSILEX/opensilex-phis-docker#3]
I tried to install PHIS using the docker recipe, however during docker `./install.sh` step, when building _phis-ws_ I get an error:
```
Access denied to: http://repo.spring.io/libs-milestone/com/twmacinta/fast-md5/2.7.1/fast-md5-2.7.1.pom
```
Trying to access this URL returns: **HTTP is not supported. Please use HTTPS**.
I looked at the `pom.xml` file, indeed specifying HTTP instead of HTTPS in the `repositories` section, but since I have never used `maven` I am not sure this is relevant...

From `phis-ws/phis2-ws/pom.xml`:
```xml
    <repositories>
        <!--REPO CRYPTAGE-->
        <repository>
            <id>spring-milestones</id>
            <url>http://repo.spring.io/libs-milestone/</url>
        </repository>
    </repositories>
```
Full log:
```bash
Step 12/30 : RUN cd /home/phis/phis-ws/phis2-ws && mvn clean install -Pprod
 ---> Running in d876959efc8f
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.mycompany:opensilex >-----------------------
[INFO] Building opensilex v0.1
[INFO] --------------------------------[ war ]---------------------------------
[...] OK dependencies [...]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2020-03-02T14:27:14Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project opensilex: Could not resolve dependencies for project com.mycompany:opensilex:war:v0.1: Failed to collect dependencies at com.twmacinta:fast-md5:jar:2.7.1: Failed to read artifact descriptor for com.twmacinta:fast-md5:jar:2.7.1: Could not transfer artifact com.twmacinta:fast-md5:pom:2.7.1 from/to spring-milestones (http://repo.spring.io/libs-milestone/): Access denied to: http://repo.spring.io/libs-milestone/com/twmacinta/fast-md5/2.7.1/fast-md5-2.7.1.pom -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ERROR: Service 'phis-ws' failed to build: The command '/bin/sh -c cd /home/phis/phis-ws/phis2-ws && mvn clean install -Pprod' returned a non-zero code: 1
```

Any idea how to fix this?
Thanks,
Jo

**Comment by Dryocopus** [comment]
I raised the same issue as #336 for phis-ws, so these can be combined.

I myself worked around it by changing http to https in a local download and that worked. But that was for an experimental project, it is very unpractical for the workflow in production, so it should indeed be fixed in the repository.

**Comment by jlegrand62** [comment]
Hello @Dryocopus,

Sorry I did not see your issue... but that does not give much hope about this issue being solved anytime soon!

To solve the problem, did you use an option with maven (overriding HTTP with HTTPS) or did you have to clone the _phis-ws_ repo and modify the config file (and the phis-ws Dockerfile)?

**Comment by Dryocopus** [comment]
Hi @jlegrand62,

I made a clone and adapted that. That breaks the docker-approach, so that will not work in production or any other meaningful environment.

A fix is easy, either you or I could make a pull request for that and ask the team for a merge, but as I understood, a whole new version of PHIS will be released in a few days, so my preference is not to get in their way now.

**Comment by jlegrand62** [comment]
Okay, thanks!

In the meantime, I have made a horrendous hack with the `sed` command in the `Dockerfile` _phis-ws_:

```
RUN cd /home/phis/phis-ws/phis2-ws && \
    sed -i "s/http\:\/\/repo\.spring\.io/https\:\/\/repo\.spring\.io/" pom.xml && \
    mvn clean install -Pprod
```

This works!

**Comment by aussieEd** [comment]
Hi There,

I too experienced this error and used your hack to get the installation working. It's progressed but I am now getting the below error. Any thoughts on how I can resolve this?

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  01:04 min
> [INFO] Finished at: 2021-02-23T03:17:22Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project opensilex: Could not resolve dependencies for project com.mycompany:opensilex:war:v0.1: Failed to collect dependencies at com.twmacinta:fast-md5:jar:2.7.1: Failed to read artifact descriptor for com.twmacinta:fast-md5:jar:2.7.1: Could not transfer artifact com.twmacinta:fast-md5:pom:2.7.1 from/to spring-milestones (https://repo.spring.io/libs-milestone/): Not authorized -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> ERROR: Service 'phis-ws' failed to build : The command '/bin/sh -c cd /home/phis/phis-ws/phis2-ws &&     sed -i "s/http\:\/\/repo\.spring\.io/https\:\/\/repo\.spring\.io/" pom.xml &&     mvn clean install -Pprod' returned a non-zero code: 1
